server:
  port: 10001


spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: a39d246a-d086-4559-9bff-89189f6d205c
    gateway:
      routes:
        - id: product-router
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
        - id: admin-router
          uri: lb://admin-service
          predicates:
            - Path=/admin-service/**
          filters:
            - StripPrefix=1
        - id: third-party-service
          uri: lb://third-party-service
          predicates:
            - Path=/third-party-service/**
          filters:
            - StripPrefix=1
        - id: member-service
          uri: lb://memeber-service
          predicates:
            - Path=/memeber-service/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
  application:
    name: gateway-service
